use evdev::KeyCode;
use uinput::event::keyboard::Key;

pub fn evdev_to_uinput(key: KeyCode) -> Option<Key> {
    match key {
        KeyCode::KEY_A => Some(Key::A),
        KeyCode::KEY_B => Some(Key::B),
        KeyCode::KEY_C => Some(Key::C),
        KeyCode::KEY_D => Some(Key::D),
        KeyCode::KEY_E => Some(Key::E),
        KeyCode::KEY_F => Some(Key::F),
        KeyCode::KEY_G => Some(Key::G),
        KeyCode::KEY_H => Some(Key::H),
        KeyCode::KEY_I => Some(Key::I),
        KeyCode::KEY_J => Some(Key::J),
        KeyCode::KEY_K => Some(Key::K),
        KeyCode::KEY_L => Some(Key::L),
        KeyCode::KEY_M => Some(Key::M),
        KeyCode::KEY_N => Some(Key::N),
        KeyCode::KEY_O => Some(Key::O),
        KeyCode::KEY_P => Some(Key::P),
        KeyCode::KEY_Q => Some(Key::Q),
        KeyCode::KEY_R => Some(Key::R),
        KeyCode::KEY_S => Some(Key::S),
        KeyCode::KEY_T => Some(Key::T),
        KeyCode::KEY_U => Some(Key::U),
        KeyCode::KEY_V => Some(Key::V),
        KeyCode::KEY_W => Some(Key::W),
        KeyCode::KEY_X => Some(Key::X),
        KeyCode::KEY_Y => Some(Key::Y),
        KeyCode::KEY_Z => Some(Key::Z),
        KeyCode::KEY_0 => Some(Key::_0),
        KeyCode::KEY_1 => Some(Key::_1),
        KeyCode::KEY_2 => Some(Key::_2),
        KeyCode::KEY_3 => Some(Key::_3),
        KeyCode::KEY_4 => Some(Key::_4),
        KeyCode::KEY_5 => Some(Key::_5),
        KeyCode::KEY_6 => Some(Key::_6),
        KeyCode::KEY_7 => Some(Key::_7),
        KeyCode::KEY_8 => Some(Key::_8),
        KeyCode::KEY_9 => Some(Key::_9),
        KeyCode::KEY_ESC => Some(Key::Esc),
        KeyCode::KEY_TAB => Some(Key::Tab),
        KeyCode::KEY_CAPSLOCK => Some(Key::CapsLock),
        KeyCode::KEY_ENTER => Some(Key::Enter),
        KeyCode::KEY_BACKSPACE => Some(Key::BackSpace),
        KeyCode::KEY_SPACE => Some(Key::Space),
        KeyCode::KEY_LEFTSHIFT => Some(Key::LeftShift),
        KeyCode::KEY_RIGHTSHIFT => Some(Key::RightShift),
        KeyCode::KEY_LEFTCTRL => Some(Key::LeftControl),
        KeyCode::KEY_RIGHTCTRL => Some(Key::RightControl),
        KeyCode::KEY_LEFTALT => Some(Key::LeftAlt),
        KeyCode::KEY_RIGHTALT => Some(Key::RightAlt),
        KeyCode::KEY_LEFTMETA => Some(Key::LeftMeta),
        KeyCode::KEY_RIGHTMETA => Some(Key::RightMeta),
        KeyCode::KEY_UP => Some(Key::Up),
        KeyCode::KEY_DOWN => Some(Key::Down),
        KeyCode::KEY_LEFT => Some(Key::Left),
        KeyCode::KEY_RIGHT => Some(Key::Right),
        KeyCode::KEY_INSERT => Some(Key::Insert),
        KeyCode::KEY_DELETE => Some(Key::Delete),
        KeyCode::KEY_HOME => Some(Key::Home),
        KeyCode::KEY_END => Some(Key::End),
        KeyCode::KEY_PAGEUP => Some(Key::PageUp),
        KeyCode::KEY_PAGEDOWN => Some(Key::PageDown),
        KeyCode::KEY_F1 => Some(Key::F1),
        KeyCode::KEY_F2 => Some(Key::F2),
        KeyCode::KEY_F3 => Some(Key::F3),
        KeyCode::KEY_F4 => Some(Key::F4),
        KeyCode::KEY_F5 => Some(Key::F5),
        KeyCode::KEY_F6 => Some(Key::F6),
        KeyCode::KEY_F7 => Some(Key::F7),
        KeyCode::KEY_F8 => Some(Key::F8),
        KeyCode::KEY_F9 => Some(Key::F9),
        KeyCode::KEY_F10 => Some(Key::F10),
        KeyCode::KEY_F11 => Some(Key::F11),
        KeyCode::KEY_F12 => Some(Key::F12),
        _ => None,
    }
}


