use evdev::KeyCode;
use uinput::event::keyboard::{Key, Misc};
#[derive(PartialEq)]
pub enum uInputKey{
    Key(Key),
    Misc(Misc)
}
pub struct mapInfo{
    pub fromKey: uInputKey,
    pub toKey: uInputKey

}
pub fn evdev_to_uinput(key: KeyCode) -> Option<uInputKey> {
    match key {
        KeyCode::KEY_A => Some(uInputKey::Key(Key::A)),
        KeyCode::KEY_B => Some(uInputKey::Key(Key::B)),
        KeyCode::KEY_C => Some(uInputKey::Key(Key::C)),
        KeyCode::KEY_D => Some(uInputKey::Key(Key::D)),
        KeyCode::KEY_E => Some(uInputKey::Key(Key::E)),
        KeyCode::KEY_F => Some(uInputKey::Key(Key::F)),
        KeyCode::KEY_G => Some(uInputKey::Key(Key::G)),
        KeyCode::KEY_H => Some(uInputKey::Key(Key::H)),
        KeyCode::KEY_I => Some(uInputKey::Key(Key::I)),
        KeyCode::KEY_J => Some(uInputKey::Key(Key::J)),
        KeyCode::KEY_K => Some(uInputKey::Key(Key::K)),
        KeyCode::KEY_L => Some(uInputKey::Key(Key::L)),
        KeyCode::KEY_M => Some(uInputKey::Key(Key::M)),
        KeyCode::KEY_N => Some(uInputKey::Key(Key::N)),
        KeyCode::KEY_O => Some(uInputKey::Key(Key::O)),
        KeyCode::KEY_P => Some(uInputKey::Key(Key::P)),
        KeyCode::KEY_Q => Some(uInputKey::Key(Key::Q)),
        KeyCode::KEY_R => Some(uInputKey::Key(Key::R)),
        KeyCode::KEY_S => Some(uInputKey::Key(Key::S)),
        KeyCode::KEY_T => Some(uInputKey::Key(Key::T)),
        KeyCode::KEY_U => Some(uInputKey::Key(Key::U)),
        KeyCode::KEY_V => Some(uInputKey::Key(Key::V)),
        KeyCode::KEY_W => Some(uInputKey::Key(Key::W)),
        KeyCode::KEY_X => Some(uInputKey::Key(Key::X)),
        KeyCode::KEY_Y => Some(uInputKey::Key(Key::Y)),
        KeyCode::KEY_Z => Some(uInputKey::Key(Key::Z)),
        KeyCode::KEY_0 => Some(uInputKey::Key(Key::_0)),
        KeyCode::KEY_1 => Some(uInputKey::Key(Key::_1)),
        KeyCode::KEY_2 => Some(uInputKey::Key(Key::_2)),
        KeyCode::KEY_3 => Some(uInputKey::Key(Key::_3)),
        KeyCode::KEY_4 => Some(uInputKey::Key(Key::_4)),
        KeyCode::KEY_5 => Some(uInputKey::Key(Key::_5)),
        KeyCode::KEY_6 => Some(uInputKey::Key(Key::_6)),
        KeyCode::KEY_7 => Some(uInputKey::Key(Key::_7)),
        KeyCode::KEY_8 => Some(uInputKey::Key(Key::_8)),
        KeyCode::KEY_9 => Some(uInputKey::Key(Key::_9)),
        KeyCode::KEY_ESC => Some(uInputKey::Key(Key::Esc)),
        KeyCode::KEY_TAB => Some(uInputKey::Key(Key::Tab)),
        KeyCode::KEY_CAPSLOCK => Some(uInputKey::Key(Key::CapsLock)),
        KeyCode::KEY_ENTER => Some(uInputKey::Key(Key::Enter)),
        KeyCode::KEY_BACKSPACE => Some(uInputKey::Key(Key::BackSpace)),
        KeyCode::KEY_SPACE => Some(uInputKey::Key(Key::Space)),
        KeyCode::KEY_LEFTSHIFT => Some(uInputKey::Key(Key::LeftShift)),
        KeyCode::KEY_RIGHTSHIFT => Some(uInputKey::Key(Key::RightShift)),
        KeyCode::KEY_LEFTCTRL => Some(uInputKey::Key(Key::LeftControl)),
        KeyCode::KEY_RIGHTCTRL => Some(uInputKey::Key(Key::RightControl)),
        KeyCode::KEY_LEFTALT => Some(uInputKey::Key(Key::LeftAlt)),
        KeyCode::KEY_RIGHTALT => Some(uInputKey::Key(Key::RightAlt)),
        KeyCode::KEY_LEFTMETA => Some(uInputKey::Key(Key::LeftMeta)),
        KeyCode::KEY_RIGHTMETA => Some(uInputKey::Key(Key::RightMeta)),
        KeyCode::KEY_UP => Some(uInputKey::Key(Key::Up)),
        KeyCode::KEY_DOWN => Some(uInputKey::Key(Key::Down)),
        KeyCode::KEY_LEFT => Some(uInputKey::Key(Key::Left)),
        KeyCode::KEY_RIGHT => Some(uInputKey::Key(Key::Right)),
        KeyCode::KEY_INSERT => Some(uInputKey::Key(Key::Insert)),
        KeyCode::KEY_DELETE => Some(uInputKey::Key(Key::Delete)),
        KeyCode::KEY_HOME => Some(uInputKey::Key(Key::Home)),
        KeyCode::KEY_END => Some(uInputKey::Key(Key::End)),
        KeyCode::KEY_PAGEUP => Some(uInputKey::Key(Key::PageUp)),
        KeyCode::KEY_PAGEDOWN => Some(uInputKey::Key(Key::PageDown)),
        KeyCode::KEY_F1 => Some(uInputKey::Key(Key::F1)),
        KeyCode::KEY_F2 => Some(uInputKey::Key(Key::F2)),
        KeyCode::KEY_F3 => Some(uInputKey::Key(Key::F3)),
        KeyCode::KEY_F4 => Some(uInputKey::Key(Key::F4)),
        KeyCode::KEY_F5 => Some(uInputKey::Key(Key::F5)),
        KeyCode::KEY_F6 => Some(uInputKey::Key(Key::F6)),
        KeyCode::KEY_F7 => Some(uInputKey::Key(Key::F7)),
        KeyCode::KEY_F8 => Some(uInputKey::Key(Key::F8)),
        KeyCode::KEY_F9 => Some(uInputKey::Key(Key::F9)),
        KeyCode::KEY_F10 => Some(uInputKey::Key(Key::F10)),
        KeyCode::KEY_F11 => Some(uInputKey::Key(Key::F11)),
        KeyCode::KEY_F12 => Some(uInputKey::Key(Key::F12)),
        KeyCode::KEY_MINUS => Some(uInputKey::Key(Key::Minus)),
        KeyCode::KEY_EQUAL => Some(uInputKey::Key(Key::Equal)),
        KeyCode::KEY_LEFTBRACE => Some(uInputKey::Key(Key::LeftBrace)),
        KeyCode::KEY_RIGHTBRACE => Some(uInputKey::Key(Key::RightBrace)),
        KeyCode::KEY_BACKSLASH => Some(uInputKey::Key(Key::BackSlash)),
        KeyCode::KEY_SEMICOLON => Some(uInputKey::Key(Key::SemiColon)),
        KeyCode::KEY_APOSTROPHE => Some(uInputKey::Key(Key::Apostrophe)),
        KeyCode::KEY_GRAVE => Some(uInputKey::Key(Key::Grave)),
        KeyCode::KEY_COMMA => Some(uInputKey::Key(Key::Comma)),
        KeyCode::KEY_DOT => Some(uInputKey::Key(Key::Dot)),
        KeyCode::KEY_SLASH => Some(uInputKey::Key(Key::Slash)),
        KeyCode::KEY_NUMLOCK => Some(uInputKey::Key(Key::NumLock)),
        KeyCode::KEY_SCROLLLOCK => Some(uInputKey::Key(Key::ScrollLock)),
        KeyCode::KEY_SYSRQ => Some(uInputKey::Key(Key::SysRq)),
        KeyCode::KEY_MUTE => Some(uInputKey::Misc(Misc::Mute)),
        KeyCode::KEY_VOLUMEUP => Some(uInputKey::Misc(Misc::VolumeUp)),
        KeyCode::KEY_VOLUMEDOWN => Some(uInputKey::Misc(Misc::VolumeDown)),
        KeyCode::KEY_PLAYPAUSE => Some(uInputKey::Misc(Misc::PlayPause)),
        KeyCode::KEY_STOPCD => Some(uInputKey::Misc(Misc::StopCD)),
        KeyCode::KEY_NEXTSONG => Some(uInputKey::Misc(Misc::NextSong)),
        KeyCode::KEY_PREVIOUSSONG => Some(uInputKey::Misc(Misc::PreviousSong)),
        _ => None,
    }
}


